name: life_friends
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  dio: ^4.0.4
  awesome_dialog: ^2.1.2
  provider: ^6.0.2
  syncfusion_flutter_datepicker: ^19.4.42
  intl: ^0.17.0
  cool_alert: ^1.1.0
  gradient_ui_widgets: ^1.0.2-nullsafety

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
