name: life_friends
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
    
  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  dio: ^4.0.4
  awesome_dialog: ^2.1.2
  provider: ^6.0.2
  syncfusion_flutter_datepicker: ^19.4.42
  intl: ^0.17.0
  cool_alert: ^1.1.0
  gradient_ui_widgets: ^1.0.2-nullsafety
  flutter_calendar_carousel: ^2.1.0
  flutter_form_bloc: ^0.20.0
  rating_dialog: ^2.0.0
  socket_io_client: ^1.0.2
  flutter_chat_bubble: ^1.0.2
  random_string: ^2.3.1
  image_picker: ^0.8.4+8

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "asset/icon.jpeg"

flutter:

  uses-material-design: true

  assets:
    - asset/

  fonts:
    - family: Copperplate
      fonts:
        - asset: asset/fonts/OPTICopperplate.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
